version: '{build}'

environment:
  matrix:
    # - platform: x86
    #   nodejs_version: '8'
    - platform: x64
      nodejs_version: '8'

build: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

before_test:
  - node --version
  - npm --version

test_script:
  - npm run test

on_success:
  - ps: .\scripts\appveyor.ps1